[package]
name = "conversor-arquivos"
version = "0.1.1"
description = "Offline file converter for Windows and Android"
authors = ["R&S CODE"]
edition = "2021"

[lib]
name = "conversor_arquivos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
